-- Enrollment Schema for Secretariat Module
-- This schema manages student enrollments and tracks their academic status

-- Create enrollments table
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    program_id BIGINT REFERENCES public.programs(id) ON DELETE CASCADE,
    academic_year TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'active', 'suspended', 'graduated', 'withdrawn', 'expelled')),
    enrollment_date DATE DEFAULT CURRENT_DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add status and enrollment_date columns to students table if they don't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'students' AND column_name = 'status') THEN
        ALTER TABLE public.students ADD COLUMN status TEXT DEFAULT 'active' 
        CHECK (status IN ('active', 'suspended', 'graduated', 'withdrawn', 'expelled'));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'students' AND column_name = 'enrollment_date') THEN
        ALTER TABLE public.students ADD COLUMN enrollment_date DATE DEFAULT CURRENT_DATE;
    END IF;
END $$;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_enrollments_student_id ON public.enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_program_id ON public.enrollments(program_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_status ON public.enrollments(status);
CREATE INDEX IF NOT EXISTS idx_students_status ON public.students(status);

-- Enable RLS on enrollments table
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- RLS Policies for enrollments
-- Secretaries, admins, and rectors can view all enrollments
CREATE POLICY "Secretaries can view all enrollments" ON public.enrollments
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role IN ('secretary', 'admin', 'rector')
        )
    );

-- Secretaries and admins can insert enrollments
CREATE POLICY "Secretaries can insert enrollments" ON public.enrollments
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role IN ('secretary', 'admin')
        )
    );

-- Secretaries and admins can update enrollments
CREATE POLICY "Secretaries can update enrollments" ON public.enrollments
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role IN ('secretary', 'admin')
        )
    );

-- Only admins can delete enrollments
CREATE POLICY "Admins can delete enrollments" ON public.enrollments
    FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
CREATE TRIGGER update_enrollments_updated_at
    BEFORE UPDATE ON public.enrollments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Comment on table
COMMENT ON TABLE public.enrollments IS 'Tracks student enrollment requests and status throughout their academic lifecycle';
