-- Create custom types
CREATE TYPE user_role AS ENUM ('student', 'professor', 'dean', 'rector', 'secretary', 'admin');

-- Profiles table (extends auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  first_name TEXT,
  last_name TEXT,
  role user_role NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Faculties
CREATE TABLE public.faculties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dean_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Programs (Study Programs / Specializations)
CREATE TABLE public.programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id BIGINT REFERENCES public.faculties(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Groups
CREATE TABLE public.groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT REFERENCES public.programs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Students (Specific details for students)
CREATE TABLE public.students (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  group_id BIGINT REFERENCES public.groups(id),
  registration_number TEXT UNIQUE
);

-- Professors (Specific details for professors)
CREATE TABLE public.professors (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  faculty_id BIGINT REFERENCES public.faculties(id)
);

-- Courses
CREATE TABLE public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  professor_id UUID REFERENCES public.professors(id),
  program_id BIGINT REFERENCES public.programs(id),
  semester INT,
  credits INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Grades
CREATE TABLE public.grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES public.students(id),
  course_id BIGINT REFERENCES public.courses(id),
  value INT CHECK (value >= 1 AND value <= 10),
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Attendance
CREATE TABLE public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES public.students(id),
  course_id BIGINT REFERENCES public.courses(id),
  date DATE DEFAULT CURRENT_DATE,
  is_present BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name, role)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', (new.raw_user_meta_data->>'role')::user_role);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
